### PR TITLE
Condense index lines where possible

### PR DESCRIPTION
**Pull request by erkyrath**
This is a proposal rather than a bug fix. It's not critical but it would make the index a bit tidier, and also make life easier for index update people (me).

The proposal is that an index stanza like

```
ice cream
    chocolate: 3.10
```

...should be condensed to

```
ice cream, chocolate: 3.10
```

This will only happen if (a) `ice cream` has no references of its own, and (b) `ice cream` has exactly one child line. (We also never condense example titles; they shouldn't have categories anyhow.)

The logic is generalized to any number of levels, so

```
ice cream
    sundae
        chocolate: 3.10
```

...would also be condensed to one line.

The effect for the index volunteer is that you can write `^^{ice cream: chocolate}` instead of `^^{ice cream, chocolate}`. The colon-separated form is better because you don't have to decide whether you're making a category. The colon will quietly turn into a comma. If you later add `^^{ice cream: vanilla}` then you'll get a two-item category with no extra editing.

Also, as a matter of tidiness, you can write `^^{|term: in context}`  instead of `^^{(term), in context+sourcepart+}`.  So there's quite a bit less need for `+sourcepart+`.

### CODE REVIEW

**Comment by erkyrath** [comment]
The code change is not too big. The hard part is the "Condense single-line categories" section. It is more or less a pinhole optimizer for the `lemma_list`. When it sees a pair of lines that should be condensed, it marks the first one as "skip" and the second one as "show both category terms, not just the final one."

(Except, again, the logic is generalized to any number of levels. This makes the code harder to read but the above description is still the right idea.)

I had to rearrange the "Render an index entry" section so that it renders N category names followed by a reference list. N, or `categories_to_show`, is usually 1, in which case the output is the same as it used to be. I've just moved the code around a bit so that it can handle the case of `N>1`.

(If N is zero, we skip the line. But this happens after the "Place an anchor" step, so we aren't breaking any cross-references.)

**Comment by erkyrath** [comment]
Here is the current list of entries affected by this change:

> announcement of darkness: printing the announcement of darkness
> announcement of light: printing the announcement of light
> backslash escapes: in extension documentation
> backticks: in extension documentation
> best route: to measure altitude
> bold: in extension documentation
> brace notation: "[(list of values) in brace notation]"
> case changing: for text produced by to say phrases
> code examples: in extension documentation
> consents: if player consents
> ended: if (scene) has ended
> Final Question Options: Table of Final Question Options
> from: inside / outside from
> happened: if (scene) has happened
> inventory details: printing inventory details of something
> links: in extension documentation
> locale description: printing the locale description of something
> locale paragraph: printing a locale paragraph about something
> lower case: (text) in lower case
> missing noun: supplying a missing noun/second noun
> nearest: (arithmetic value) to the nearest (arithmetic value)
> nearest whole number: (real number) to the nearest whole number
> nondescript items: listing nondescript items of something
> notable locale objects: choosing notable locale objects for something
> paragraph: writing a paragraph about
> parser's choice: clarifying the parser's choice of something
> pattern matching: phrase definitions
> provides: provision relation
> refusal to act: printing a refusal to act in the dark
> room description details: printing room description details of something
> sentence case: (text) in sentence case
> strikethrough: in extension documentation
> syntax colouring: in extension documentation
> title case: (text) in title case
> to-do items: in extension documentation
> together: group (description of objects) together
> transcripts: creating with the TEST command
> upper case: (text) in upper case
> which: asking which do you mean
> while (condition): arbitrary conditions for rules
> whole number: (real number) to the nearest whole number

**Comment by erkyrath** [comment]
I am not proposing to go through the manual and replace commas with colons in every index term! Although I may do a bit of it. The aim is to make life incrementally easier in the future.

**Comment by ganelson** [comment]
Elegant! And I do think that's good index style in general - for example, for "transcripts: creating with the TEST command".

But perhaps condensation should only allowed when the categories are the same? Consider "consents: if player consents". Here "if player consents" is a phrase and is tinted accordingly, with a subscripted "phrase" marker. But "consents, if player consents" is not.

**Comment by erkyrath** [comment]
Hm. The current behavior is to turn:

snap1

...to...

snap2

It retains the color and marker. This seems like what we want.

The part before and after the comma have different headword types, but this is already common. The effect is analogous to index lines like `^^{(condition), as name for value property+sourcepart+}`.

**Comment by ganelson** [comment]
Yes, I'm persuaded by that! Sold, and thanks.

**Pull request merged**
