### PR TITLE
story title in transcript rule response patch

### PR DESCRIPTION
**Pull request by zedlopez**
The existing code has an "of" hanging; it looks like the story title was meant to go there.

This passes `make check`.

### CODE REVIEW

**Comment by ganelson** [comment]
It's not hanging, though, surely, because when this response is issued it is immediately followed by the banner for the game, which opens with the title? This is a convention going back to the Infocom games, I believe. It doesn't look strange to me on screen once a transcript begins. Do other people think this is wrong?

**Comment by zedlopez** [comment]
After submitting that I had some misgivings that that might have been the intent. There had been discussion here:
https://intfiction.org/t/cutting-the-forced-version-command-out-of-transcript-on-process/56339
where the water was muddied by my having cleverly directed the version info to the transcript only but not the screen, so the screen was only getting "Start of a transcript of". But afterwards I had gone to an old conventional transcript and I thought the "of" looked  hanging there, too, even though the story title was underneath, separated by a blank line. So: two people with freshly skewed perspectives from having been looking at a variant thought it was wrong.  Anyway, this was only ever a small matter. Discard at will.

**Comment by ganelson** [comment]
Would a compromise be to end the current response with a colon, i.e, to be "Start of a transcript of:"? That might make it clearer that what follows below is connected to this message.

**Comment by zedlopez** [comment]
I think that would be a small but true improvement.

**Comment by ganelson** [comment]
Cool. I'm at the wrong desk to do this right now, but if you'd like to commit a change to this PR to put the colon in, I'll then merge.

**Comment by ganelson** [comment]
Excellent!

**Pull request merged**
