### PR TITLE
Fix Jira bug I7-1919 [Mantis bug 1955] -- Extension doc formatting

### PR DESCRIPTION
**Pull request by neroden**
I said several years ago (before Inform was open source) that I could probably fix this bug if I had access to the source.

I have now fixed it.

The primary issue was problems in the core logic for identifying headings and examples; they were basically disabled, and had multiple logic bugs on top of that.  They have been re-enabled, rewritten, tested, and they work fine.  A secondary issue was obsolete HTML, which has been modernized.

In addition to core logic fixes, and HTML tag structure fixes, this patch now allows "Chapter - Something" in extension documentation as well as "Chapter: Something", and "Example - Something" as well as "Example: Something".  This is so that extension authors can write their headings in the documentation the same way they write them in the code (which always uses "Chapter - Something").  This is highly desirable.

This has been tested on Linux.  The IDE formats the HTML pages correctly, the links work, everything opens and closes, it's good.  Also passes "make check".

### CODE REVIEW

**Comment by neroden** [comment]
Mental confusion regarding bug numbers.  I'll put them both in the title to stop confusing myself.

**Comment by neroden** [comment]
In case you're wondering about the HTML:
(1) There were several places where set_body_text was called which were *not* trying to make a new paragraph, so the <p> / </p> markers were removed from set_body_text and put into the callers which did want a new paragraph.
(2) It is best practice to put style markers *outside* an <a href> anchor if possible, so this was done.
(3) <a name=""> anchors are obsolete, so were replaced with <span id="">.  One of these had an invalid HTML structure (it was like <a><b></a></b>, which isn't valid) and needed to be rearranged.
(4) When this was done, I noted that the examples in the index had nothing separating the letter from the example name, so I added an M dash.
(5) There were a couple of other misplaced paragaph starts.

**Comment by ganelson** [comment]
I'm accepting this, with thanks - this has always been a rather unloved section of the compiler, and you've clearly improved it.

There are still some issues which in an ideal world we would address. If Inform writes the documentation page for an extension, it currently doesn't quite close its tags in the proper sequence, according to the debugging log, which contains stuff like:

Trying to close p at line 322 of 'services/html-module/Chapter 2/Documentation Renderer.w', but:
Tag error: closed HTML tag which wasn't open
HTML tag stack:
    1. body (opened at line 370 of '/Users/gnelson/Natural Inform/inweb/foundation-module/Chapter 5/HTML.w')
    2. html (opened at line 236 of '/Users/gnelson/Natural Inform/inweb/foundation-module/Chapter 5/HTML.w')


Trying to close body at line 374 of '/Users/gnelson/Natural Inform/inweb/foundation-module/Chapter 5/HTML.w', but:
Tag error: closed HTML tag which wasn't open
HTML tag stack:
    1. p (opened at line 325 of 'services/html-module/Chapter 2/Documentation Renderer.w')
    2. html (opened at line 236 of '/Users/gnelson/Natural Inform/inweb/foundation-module/Chapter 5/HTML.w')

These are not errors halting compilation, they're just diagnostics which are supposed to make my conscience trouble me until I fix it. So far, though, I seem to be good at ignoring my conscience. Is it worth addressing these tag mis-pairings now, while we're working on this section of code?

In the mean time, thanks once more, and I am very happy to close I7-1919.

**Comment by neroden** [comment]
Thank you! 

You have piqued my interest.  I took a look at the tag matching issue.  Matching the tags is actually very finicky work.  Both of these particular examples are from "Handle a Paragraph Break".  I'd probably have to see the whole log to sort out what's actually going on, because to figure out where the error is, I have to track the opening and closing of each tag on a particular page where I know how the page is laid out.  How can I generate this particular debug log for a particular extension file?

**Comment by ganelson** [comment]
Always good to be piqued!

If you're running inform7 from the command line, then supplying -log FILENAME will write the debugging log to the named file; on any run from the Inform apps, it will be generated inside the project's Build subdirectory. The log is quite configurable (see https://ganelson.github.io/inform/secrets.html), but in any case inform7 (and inbuild) always log any detected HTML mismatches like these, so you don't need to do anything special to have these diagnostics present.

**Pull request merged**
